name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Checkout
        uses: actions/checkout@v2
      - name: Expo GitHub Action
        uses: expo/expo-github-action@7.1.1
        with:
          expo-version: latest
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: expo build:web
          start: expo start -w
          wait-on: http://localhost:19006
          config: baseUrl=http://localhost:19006
